#!/usr/bin/env node
// Phase-2 OneDrive-mirror live verification against the deployed SWA.
// Exercises: config defaults + round-trip, seed→approve on-mirror (non-fatal), manual mirror,
// and gdrive Phase-3 deferral. Reuses the same seroval encode/decode + fn-id resolution as huddle.mjs.
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { toJSONAsync } from "seroval";
import { defaultSerovalPlugins } from "@tanstack/router-core";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const BASE = process.env.HUDDLE_BASE || "https://icy-flower-0f415200f.7.azurestaticapps.net";
const CALLER = { entra_email: process.env.HUDDLE_CALLER || "von.ellis@enterpriseds.io" };
const plugins = defaultSerovalPlugins;

function ids() {
  const dir = path.resolve(process.cwd(), ".output/server");
  const f = fs.readdirSync(dir).find((x) => x.includes("server-fn-resolver"));
  const s = fs.readFileSync(path.join(dir, f), "utf8");
  const re = /"([a-f0-9]{64})"\s*:\s*\{[^}]*?functionName:\s*"([a-zA-Z0-9_]+)_createServerFn_handler"/g;
  const map = {}; let m;
  while ((m = re.exec(s))) map[m[2]] = m[1];
  return map;
}
// Real seroval constant indices (verified via toJSONAsync): booleans matter here, unlike the
// string-only huddle.mjs harness whose CONST map is incomplete.
const CONST = { 0: null, 1: undefined, 2: true, 3: false, 4: -0, 5: Infinity, 6: -Infinity, 7: NaN };
function dec(root) {
  const reg = new Map();
  function w(n) {
    if (n == null || typeof n !== "object") return n;
    switch (n.t) {
      case 0: case 1: return n.s;
      case 3: return typeof n.s === "string" ? BigInt(n.s) : n.s;
      case 2: return n.s in CONST ? CONST[n.s] : undefined;
      case 7: return reg.get(n.i);
      case 9: { const a = []; if (n.i != null) reg.set(n.i, a); for (const it of n.a ?? []) a.push(w(it)); return a; }
      case 10: case 11: { const o = {}; if (n.i != null) reg.set(n.i, o); const k = n.p?.k ?? [], v = n.p?.v ?? []; for (let j = 0; j < k.length; j++) o[k[j]] = w(v[j]); return o; }
      default: return n.s ?? null;
    }
  }
  return w(root);
}
async function call(id, payload) {
  const body = JSON.stringify(await toJSONAsync({ data: payload }, { plugins }));
  const res = await fetch(`${BASE}/_serverFn/${id}`, {
    method: "POST",
    headers: { "Content-Type": "application/json", "x-tsr-serverFn": "true", accept: "application/json" },
    body,
  });
  const txt = await res.text();
  let node; try { node = JSON.parse(txt); } catch { return { httpError: res.status, raw: txt.slice(0, 300) }; }
  let d; try { d = dec(node); } catch (e) { return { decodeErr: String(e), raw: txt.slice(0, 300) }; }
  return d?.result ?? d;
}

const j = (o) => JSON.stringify(o);
const FN = ids();
for (const need of ["getMirrorConfigFn", "setMirrorConfigFn", "mirrorArtifactFn", "createArtifactFn", "reviewArtifactFn", "getArtifactFn"]) {
  if (!FN[need]) { console.error("MISSING fn id:", need); process.exit(1); }
}

(async () => {
  console.log("BASE:", BASE, "  caller:", CALLER.entra_email, "\n");

  // AC: config read returns the three booleans (DB row or defaults).
  const c0 = await call(FN.getMirrorConfigFn, { caller: CALLER });
  console.log("1) getMirrorConfig →", j(c0.config ?? c0));

  // AC: round-trip a change then restore, proving durable per-destination toggles.
  const flip = { mirror_on_approve: false, onedrive_enabled: true, gdrive_enabled: false };
  const sset = await call(FN.setMirrorConfigFn, { caller: CALLER, ...flip });
  const c1 = await call(FN.getMirrorConfigFn, { caller: CALLER });
  console.log("2) set", j(flip), "→ ok=", sset.ok, " read back →", j(c1.config ?? c1));
  // restore all-on
  await call(FN.setMirrorConfigFn, { caller: CALLER, mirror_on_approve: true, onedrive_enabled: true, gdrive_enabled: true });
  const c2 = await call(FN.getMirrorConfigFn, { caller: CALLER });
  console.log("   restored →", j(c2.config ?? c2));

  // AC: seed a test artifact, then approve → mirror is attempted; approve MUST succeed regardless.
  const name = `phase2-mirror-test-${String(Date.now()).slice(-6)}.md`;
  const seed = await call(FN.createArtifactFn, {
    caller: CALLER, folder: "_mirror-test", name, mime: "text/markdown",
    text: "# Phase 2 mirror test\nAuto-generated by mirror-verify.mjs. Safe to delete.",
  });
  console.log("\n3) createArtifact →", j(seed));
  if (!seed.ok) { console.log("   (cannot proceed to approve without a seeded artifact)"); return; }

  const appr = await call(FN.reviewArtifactFn, { caller: CALLER, id: seed.id, action: "approve" });
  console.log("4) approve →  ok=", appr.ok, " status=", appr.artifact?.status, " mirror=", j(appr.mirror));
  console.log("   → approve-succeeds-despite-mirror:", appr.ok === true ? "PASS" : "FAIL");
  if (appr.mirror) {
    const okOrConsent = appr.mirror.ok === true || appr.mirror.needsConsent === true;
    console.log("   → mirror is success-or-actionable-403:", okOrConsent ? "PASS" : `FAIL (${j(appr.mirror)})`);
    if (appr.mirror.ok) console.log("   → OneDrive webUrl:", appr.mirror.onedrive_url);
  }

  // AC: manual "Mirror now" (onedrive) — same success-or-consent contract.
  const man = await call(FN.mirrorArtifactFn, { caller: CALLER, id: seed.id, destination: "onedrive" });
  console.log("\n5) mirrorArtifact(onedrive) →", j(man));

  // AC: gdrive is deferred to Phase 3 (never a crash, a clear note).
  const g = await call(FN.mirrorArtifactFn, { caller: CALLER, id: seed.id, destination: "gdrive" });
  console.log("6) mirrorArtifact(gdrive)   →", j(g), " deferred:", g.deferred === true ? "PASS" : "FAIL");
})();
