/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiPublicTasksSyncRouteImport } from './routes/api/public/tasks-sync'
import { Route as ApiPublicRunTurnRouteImport } from './routes/api/public/run-turn'
import { Route as ApiPublicRunGroomingRouteImport } from './routes/api/public/run-grooming'
import { Route as ApiPublicRunCeremonyRouteImport } from './routes/api/public/run-ceremony'
import { Route as ApiPublicAuthTraceRouteImport } from './routes/api/public/auth-trace'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicTasksSyncRoute = ApiPublicTasksSyncRouteImport.update({
  id: '/api/public/tasks-sync',
  path: '/api/public/tasks-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunTurnRoute = ApiPublicRunTurnRouteImport.update({
  id: '/api/public/run-turn',
  path: '/api/public/run-turn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunGroomingRoute = ApiPublicRunGroomingRouteImport.update({
  id: '/api/public/run-grooming',
  path: '/api/public/run-grooming',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunCeremonyRoute = ApiPublicRunCeremonyRouteImport.update({
  id: '/api/public/run-ceremony',
  path: '/api/public/run-ceremony',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthTraceRoute = ApiPublicAuthTraceRouteImport.update({
  id: '/api/public/auth-trace',
  path: '/api/public/auth-trace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/auth-trace': typeof ApiPublicAuthTraceRoute
  '/api/public/run-ceremony': typeof ApiPublicRunCeremonyRoute
  '/api/public/run-grooming': typeof ApiPublicRunGroomingRoute
  '/api/public/run-turn': typeof ApiPublicRunTurnRoute
  '/api/public/tasks-sync': typeof ApiPublicTasksSyncRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/auth-trace': typeof ApiPublicAuthTraceRoute
  '/api/public/run-ceremony': typeof ApiPublicRunCeremonyRoute
  '/api/public/run-grooming': typeof ApiPublicRunGroomingRoute
  '/api/public/run-turn': typeof ApiPublicRunTurnRoute
  '/api/public/tasks-sync': typeof ApiPublicTasksSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/auth-trace': typeof ApiPublicAuthTraceRoute
  '/api/public/run-ceremony': typeof ApiPublicRunCeremonyRoute
  '/api/public/run-grooming': typeof ApiPublicRunGroomingRoute
  '/api/public/run-turn': typeof ApiPublicRunTurnRoute
  '/api/public/tasks-sync': typeof ApiPublicTasksSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/api/public/auth-trace'
    | '/api/public/run-ceremony'
    | '/api/public/run-grooming'
    | '/api/public/run-turn'
    | '/api/public/tasks-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/sitemap.xml'
    | '/'
    | '/api/public/auth-trace'
    | '/api/public/run-ceremony'
    | '/api/public/run-grooming'
    | '/api/public/run-turn'
    | '/api/public/tasks-sync'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/'
    | '/api/public/auth-trace'
    | '/api/public/run-ceremony'
    | '/api/public/run-grooming'
    | '/api/public/run-turn'
    | '/api/public/tasks-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicAuthTraceRoute: typeof ApiPublicAuthTraceRoute
  ApiPublicRunCeremonyRoute: typeof ApiPublicRunCeremonyRoute
  ApiPublicRunGroomingRoute: typeof ApiPublicRunGroomingRoute
  ApiPublicRunTurnRoute: typeof ApiPublicRunTurnRoute
  ApiPublicTasksSyncRoute: typeof ApiPublicTasksSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/tasks-sync': {
      id: '/api/public/tasks-sync'
      path: '/api/public/tasks-sync'
      fullPath: '/api/public/tasks-sync'
      preLoaderRoute: typeof ApiPublicTasksSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/run-turn': {
      id: '/api/public/run-turn'
      path: '/api/public/run-turn'
      fullPath: '/api/public/run-turn'
      preLoaderRoute: typeof ApiPublicRunTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/run-grooming': {
      id: '/api/public/run-grooming'
      path: '/api/public/run-grooming'
      fullPath: '/api/public/run-grooming'
      preLoaderRoute: typeof ApiPublicRunGroomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/run-ceremony': {
      id: '/api/public/run-ceremony'
      path: '/api/public/run-ceremony'
      fullPath: '/api/public/run-ceremony'
      preLoaderRoute: typeof ApiPublicRunCeremonyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth-trace': {
      id: '/api/public/auth-trace'
      path: '/api/public/auth-trace'
      fullPath: '/api/public/auth-trace'
      preLoaderRoute: typeof ApiPublicAuthTraceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicAuthTraceRoute: ApiPublicAuthTraceRoute,
  ApiPublicRunCeremonyRoute: ApiPublicRunCeremonyRoute,
  ApiPublicRunGroomingRoute: ApiPublicRunGroomingRoute,
  ApiPublicRunTurnRoute: ApiPublicRunTurnRoute,
  ApiPublicTasksSyncRoute: ApiPublicTasksSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
